<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>verilang</groupId>
    <artifactId>verilang-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <rascal.version>0.41.2</rascal.version>
        <typepal.version>0.11.5</typepal.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.rascalmpl</groupId>
            <artifactId>rascal</artifactId>
            <version>${rascal.version}</version>
        </dependency>
        <dependency>
            <groupId>org.rascalmpl</groupId>
            <artifactId>typepal</artifactId>
            <version>${typepal.version}</version>
        </dependency>
    </dependencies>
</project>
